# Generated by Django 3.0.1 on 2023-08-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200211_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
